# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [5]:
A = np.arange(1, 16).reshape(3,5)


In [24]:
print(A)
print(A.shape)
print(A.ndim)
print(A.dtype.name)
print(A.itemsize)
print(A.size)
type(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)
2
int32
4
15


numpy.ndarray

In [17]:
A.shape
(3, 5)
A.ndim
2
A.dtype.name
'int32'
A.itemsize
4
A.size
15
type(A)
np.ndarray
B = np.array([6, 7, 8])
B
np.array([6, 7 ,8])
type(B)

numpy.ndarray

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [25]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [27]:
B * C

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [28]:
B - C

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

In [29]:
B @ C

array([[12., 12., 12.],
       [30., 30., 30.],
       [48., 48., 48.]])

### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [30]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
np.exp(B)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [32]:
np.min(B)

1

In [39]:
B.min(axis=0)

array([1, 2, 3])

In [40]:
B.min(axis=1)


array([1, 4, 7])

In [44]:
B.argmin()

0

In [45]:
B.argmin(axis=1)

array([0, 0, 0], dtype=int64)

In [47]:
B.sum()

45

In [48]:
B.mean(axis=1)

array([2., 5., 8.])

In [59]:
np.median(B, axis=1)

array([2., 5., 8.])

### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [60]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [65]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

Numpy gör så att dem axlarna du anger, kommer ha "slicing", dem axlerna som du inte har med appliceras en implict : som gör att alla element inkluderas i dem axlarna du väljer. Detta gör att du inte behöver ange alla axlar som du vill "slicea"

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [66]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [67]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [68]:
for element in A.flat:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [85]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


a = np.arange(30) = skapar och ränkar ut en numpay array med 30 element. 
b = a.reshape((2, 3, -1)) = Omformar array från en 2D till en 3D-array med formen (2, 3, -1,) där 2 står för hur många "lager" som elementen ska formeteras i, 3 står för hur många rader som ska bildas i varje "lager" och får då 3 "axes". -1 gör så att Numpy förstår att man vill att alla 30 element ska få plats i dessa 2 blocken som man vill omformera. 




# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [87]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [88]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [89]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [264]:
def add_mult_matrices(matrix1, matrix2, add_or_mult):
    if not isinstance(matrix1, np.ndarray):
        raise ValueError('Both inputs must be the type of numpy.ndarrys')
    if not isinstance(matrix2, np.ndarray):
        raise ValueError('Both inputs must be the type of numpy.ndarrys')
    
    if add_or_mult not in('add', 'multiply'):
        raise ValueError('the add_or_mult must be in add of multiply')
    
    if add_or_mult == 'add':
        if matrix1.shape != matrix2.shape:
            raise ValueError('Matrics must be the same size for add')
        return matrix1 + matrix2 
    
    if add_or_mult == 'multiply':
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError('Number of columns in the first matrix must equal the number of rows in the second matrix for multiplication')
        return np.dot(matrix1, matrix2)
    
matrix1 = np.array([[1, 2], [2, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
    
add_result= add_mult_matrices(matrix1, matrix2, 'add')
mult_result = add_mult_matrices(matrix1, matrix2, 'multiply')

print(add_result)
print(mult_result)

# add_result1= add_mult_matrices(matrix1, matrix2, 'tjoho') test om det skulle komma upp ett valueerror




    

[[ 6  8]
 [ 9 12]]
[[19 22]
 [38 44]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. 

In [265]:
# Uppgift 10.1.1
 
x = np.array([4, 3])

# a) Svar: 1 x 2 
print("a")
print(x.shape)
# b) svar:    (5 x 4)
#             (5 x 3) = (20,15)
five_x = 5* x
print("b")
print(five_x)

# c) svar:    (3 x 4)
#             (3 x 3) = (12,9)

three_x = 3* x
print("c")
print(three_x)

# d) svar:    (5 x 4)
#             (5 x 3) = (20,15)
#             (3 x 4)
#             (3 x 5) = (12,15) 
#             (20,15) + (12,9) = (32,24)

five_x = 5* x 
three_x = 3* x
print("d")
print(five_x + three_x)
            
# e) svar:    (8 x 4)
#             (8 x 3) = (32,24)

eight_x = 8* x
print("e")
print(eight_x)

# f) svar:    (4 x 4)
#             (4 x 3) = (16, 12) - (4, 3) = (12, 9)

four_x = 4* x
print("f")
print(four_x - x)

# g) svar: Det blir en Kolumvektor istället (4)
#                                           (3)
x_transportering = x.reshape(2, 1)
print("g")
print(x_transportering)
  
# h) svar: Det är inte definerat då en vektor är 2 x 1 och andra är 1 x 2

print("h")
print(x + x.T)

# i) svar: 25. Uträkning gåt ett att göra här.  -->

norm = np.linalg.norm(x)
print("i")
print(norm)







a
(2,)
b
[20 15]
c
[12  9]
d
[32 24]
e
[32 24]
f
[12  9]
g
[[4]
 [3]]
h
[8 6]
i
5.0


In [237]:
# Uppgift 10.1.2

v = np.array([3, 7, 0, 11])

# a) svar: 4

print("a")
print(v.shape)

# b) svar: 6 14 0 22

two_v = 2* v
print("b")
print(two_v)

# c) svar: [21, 49, 0, 77]

five_v = 5* v
two_v = 2* v
print("c")
print(five_v + two_v)

# d) svar: [6, 14, 0, 22]

four_v = 4* v
two_v = 2* v
print("d")
print(four_v - two_v)

#e) svar: [3 7 0 11] 

v_transportering = v.reshape(1, -1)
print("e")
print(v_transportering)

#f) svar: 13.3790...

norm = np.linalg.norm(v)
print("f")
print(norm)

a
(4,)
b
[ 6 14  0 22]
c
[21 49  0 77]
d
[ 6 14  0 22]
e
[[ 3  7  0 11]]
f
13.379088160259652


In [165]:
# Uppgift 10.1.3 

v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

# a) svar: 7.14142842..

norm = np.linalg.norm(v1)
print("a")
print(norm)

# b) svar: 3.26844508.. 

norm1 = np.linalg.norm(v1)
norm2 = np.linalg.norm(v2)
print("b")
print(norm1 - norm2)


 

7.14142842854285
3.2684450823354334


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [239]:
# Uppgift 10.2.1

# a) svar: [4 2 -2 2 -2 2]

A = np.array([[2, 1, -1], [1, -1, 1]])

two_a = 2* A
print("a")
print(two_a)

# b) svar: [0 4 -3 0 2 4]

B = np.array([[4, -2, 1], [2, -4, -2]])

print("b")
print(B)
print(B - two_a)

# c) svar: 

C = np.array([[1, 2], [2, 1]])
E = np.array([1, 2])

print("c")
try:
    three_C = 3* C
    two_E = 2* E
except:
    print('Ej definerad')

# d) svar: [2, 2, 2, 2]

D = np.array([[3, 4], [4, 3]])

two_D = 2* D
three_C = 3* C

print("d")
print(two_D - three_C)

# e) svar: [9, 12, 12, 9]
print("e")
print(D.T + two_D)

# f) svar: [-4 -4 -4 -4]
two_C = 2* C
two_D = 2* D
print("f") 
print(two_C.T - two_D.T)

# g) svar: 
print("g")
try:
    print(A.T - B)
except:
    print('ej definerad')


# h)
print("h.")
print(A.T @ C)
 

# i) 
print("i")
print(C @ D)

# j)
print("j")
print(C @ B)

# k)
I = np.array([[1, 0], [0, 1]])
print("k")
print(C @ I)

# l)
print("l")
print(A @ B.T)







a
[[ 4  2 -2]
 [ 2 -2  2]]
b
[[ 4 -2  1]
 [ 2 -4 -2]]
[[ 0 -4  3]
 [ 0 -2 -4]]
c
d
[[3 2]
 [2 3]]
e
[[ 9 12]
 [12  9]]
f
[[-4 -4]
 [-4 -4]]
g
ej definerad
h.
[[ 4  5]
 [-1  1]
 [ 1 -1]]
i
[[11 10]
 [10 11]]
j
[[  8 -10  -3]
 [ 10  -8   0]]
k
[[1 2]
 [2 1]]
l
[[5 2]
 [7 4]]


In [266]:
# Uppgift 10.2.2 Definera matrisen 

A = np.array([[2, 3 ,4], [5, 4, 1]])

print("uppgift_10.2.2")
A_T = A.T
A @ A_T

uppgift_10.2.2


array([[29, 26],
       [26, 42]])

In [250]:
# uppgift 10.2.3 

A = np.array([[1, 2],[2, 4]])
B = np.array([[2, 1],[1, 3]])
C = np.array([[4, 3],[0, 2]])

AB = A@B
AC = A@C 
assert (AB == AC).all()
assert not (B == C).all()

In [275]:
print(AB == AC)

[[ True  True]
 [ True  True]]


In [274]:
print(B == C)

[[False False]
 [False False]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [251]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [267]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [270]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)
print(v1.base)

[  0   1   2 123]
[  2 123]
None


First of all, you can type print(v1.base) if its returns "none", then you can tell if the base attribut of ndarray is a view or a copy
A veiw shares the same data as the orginal array witch means if you change something in the view array its affect the orginal array. The copy array is independent from the orginal array so changes in the copy array wont effect the orginal array. V1 is the base array, meaning v2 is a view of v1. If you do changeses in v2, v1 will also changes becuase its the same memory.  